language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - sed -ie "s/XXX_VUE_APP_MARVEL_API_KEY_XXX/$MARVEL_API_KEY/g" .env
  - yarn build
cache:
  yarn: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master
  target_branch: gh-pages
  fqdn: serverless-heroes.endofco.de